# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : wezterm
version    : 20240203
release    : 1
source     :
    - https://github.com/wezterm/wezterm/archive/refs/tags/20240203-110809-5046fc22.tar.gz : 3a02a68016ef48cdb2127308be20acafe94a568411e95b0e64dc590cf877b401
homepage   : https://wezterm.org/
license    : MIT
component  : system.utils
summary    : A GPU-accelerated cross-platform terminal emulator
description: |
    A GPU-accelerated cross-platform terminal emulator and multiplexer implemented in Rust.
networking : true
builddeps  :
  - pkgconfig(wayland-client)
  - pkgconfig(wayland-protocols)
  - pkgconfig(xkbcommon)
  - pkgconfig(x11)
  - pkgconfig(xcb)
  - pkgconfig(fontconfig)
  - pkgconfig(freetype2)
  - pkgconfig(harfbuzz)
  - pkgconfig(openssl)
  - pkgconfig(egl)
  - pkgconfig(gl)
  - rust
setup      : |
    %cargo_fetch

build      : |
    %cargo_build --all-features

install    : |
    %cargo_install
